@startuml

title C++ => Java 调用时序图

== 服务引用 ==

"C++" -> 代理层: 1. 服务引用配置
代理层 -> 注册中心: 2. 服务发现

== 服务调用 ==

"C++" -> 代理层: 3. Thrift 调用
代理层 -> Java: 4. RPC 服务泛化调用
Java -> 代理层: 5. RPC 服务泛化响应
代理层 -> "C++": 6. Thrift 响应

@enduml